/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-jLrALjdzbljMPa18q4KOnE5Rgg-KImv3g0dveqVCshbnMa7MVL4NTBvknT8AcLi2vneIqBntYxP3KbHr4FV2083g-PnekrXS8mTgbgQUVbOYLQYZv0T9WAvC",
  "tt": "tt-1-pjqW-uZ5BGW36uSgRHDvp3ajFcfYh5aPt7zIYgl8vO0=",
  "version": "2020-11-20"
}

export default ebconfig;